version: '2'
services:
    managementportal-postgresql:
        image: bitnami/postgresql:12
        environment:
            - POSTGRESQL_USERNAME=radarcns
            - POSTGRESQL_PASSWORD=radarcns
            - POSTGRESQL_DATABASE=managementportal
